// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace SkillstormTelecom.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240402192412_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BillID");

                    b.Property<DateTime>("BillingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("BillingDate");

                    b.Property<string>("OtherBillDetails")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Other bill details");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float")
                        .HasColumnName("TotalAmount");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeviceID");

                    b.Property<string>("OtherDeviceDetails")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Other device details");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PhoneNumber");

                    b.Property<Guid>("PlanID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Entities.PhonePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PlanID");

                    b.Property<int>("DeviceLimit")
                        .HasColumnType("int")
                        .HasColumnName("DeviceLimit");

                    b.Property<string>("OtherPlanDetails")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Other plan details");

                    b.Property<string>("PlanName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PlanName");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("Price");

                    b.HasKey("Id");

                    b.ToTable("PhonePlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("05444900-9ac7-4dd5-b69f-221c098a1493"),
                            DeviceLimit = 1,
                            OtherPlanDetails = "Unlimited talk and text with 5GB of data.",
                            PlanName = "Unlimited Talk and Text",
                            Price = 50.0
                        },
                        new
                        {
                            Id = new Guid("a0233acc-383c-4a9e-b867-34d7ba382512"),
                            DeviceLimit = 2,
                            OtherPlanDetails = "Unlimited talk, text, and data.",
                            PlanName = "Unlimited Everything",
                            Price = 75.0
                        },
                        new
                        {
                            Id = new Guid("319cf1f0-ab87-4a64-845f-9b873a547872"),
                            DeviceLimit = 1,
                            OtherPlanDetails = "500 minutes, 500 texts, and 1GB of data.",
                            PlanName = "Basic Plan",
                            Price = 25.0
                        },
                        new
                        {
                            Id = new Guid("2d2f6606-6325-4e26-9c54-e8eb44521e85"),
                            DeviceLimit = 4,
                            OtherPlanDetails = "Unlimited talk, text, and data for 4 devices.",
                            PlanName = "Family Plan",
                            Price = 100.0
                        });
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a55f01b-1cd0-4848-b7ae-86c40b1ad289"),
                            Email = "jonsablinski@gmail.com",
                            Password = "password",
                            Username = "Jon&Linda"
                        },
                        new
                        {
                            Id = new Guid("12ae765a-189b-4194-81e6-0b4046f32853"),
                            Email = " bbop102@yahoo.com",
                            Password = "SinginBobby200",
                            Username = "BillieBob"
                        },
                        new
                        {
                            Id = new Guid("2a4425e8-f6bf-4d34-9c8d-5236751f7635"),
                            Email = "sallyfields1968@gmail.com",
                            Password = "theSally!0!",
                            Username = "Sally"
                        });
                });

            modelBuilder.Entity("Entities.UserPhonePlan", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlanID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserID", "PlanID");

                    b.ToTable("UserPhonePlans");
                });
#pragma warning restore 612, 618
        }
    }
}
